Repository kod3rsStore/Frontend, pull requests merged in 2020-06, with the labels that each got.

#42 Button color
  src/Frontend/public/images/icons-512.png
  src/Frontend/public/img/icons/icon-128x128.png
  src/Frontend/public/img/icons/icon-144x144.png
  src/Frontend/public/img/icons/icon-152x152.png
  src/Frontend/public/img/icons/icon-192x192png.png
  src/Frontend/public/img/icons/icon-384x384.png
  src/Frontend/public/img/icons/icon-512x512.png
  src/Frontend/public/img/icons/icon-72x72.png
  src/Frontend/public/img/icons/icon-96x96.png
  src/Frontend/public/index.html
  src/Frontend/public/manifest.json
  src/Frontend/public/worker.js
  src/Frontend/src/Components/Atoms/Button/button.css
  src/Frontend/src/Components/Modal/Modal.css
  src/Frontend/src/Styles/Header.css
  src/Frontend/src/index.js
Labels: frontend

#45 Add paypal paymentoption
  src/Frontend/package-lock.json
  src/Frontend/package.json
  src/Frontend/src/App.js
  src/Frontend/src/Components/Cart2.jsx
  src/Frontend/src/Components/CheckOut.jsx
  src/Frontend/src/Components/ProductDtl.js
  src/Frontend/src/Containers/checkOutPage.jsx
  src/Frontend/src/Styles/components/checkOut.css
Labels: frontend

#47 46 create ci flow
  .gitlab-ci.yml
  README.md
  docker-compose.prod.yml
  docker-compose.yml
  src/Frontend/Dockerfile
  src/SSR-server/Dockerfile
Labels: CI / CD

#48 modify the CI/CD
  docker-compose.prod.yml
  src/Frontend/package-lock.json
  src/Frontend/package.json
  src/Frontend/public/index.html
  src/Frontend/src/Components/CartProductCard.jsx
  src/Frontend/src/Components/CheckOut.jsx
  src/Frontend/src/Components/Home.js
  src/Frontend/src/Components/Products2.jsx
  src/Frontend/src/Components/productCardList.jsx
  src/Frontend/src/Components/productCardListSearch.jsx
  src/Frontend/src/Styles/components/main.css
  src/Frontend/src/index.js
  src/SSR-server/config/index.js
  src/SSR-server/index.js
  src/SSR-server/utils/auth/strategies/google.js
  src/SSR-server/utils/auth/strategies/oauth.js
Labels: CI / CD

#53 Fixed the docker-compose-prod file
  README.md
  docker-compose.prod.yml
Labels: CI / CD

#54 fixed the docker-compose.prod.yml
  docker-compose.prod.yml
Labels: CI / CD

#64 fixed css problems
  src/frontend/components/Layout.jsx
  src/frontend/containers/goHome.jsx
  src/frontend/routes/ServerRoutes.jsx
  src/frontend/styles/components/Layout.styl
Labels: bug
